/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onelock;

/**
 *
 * @author EiderAndrésGonzálezS
 */
public class onelock extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public onelock() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        poliedro_r1 = new javax.swing.JButton();
        poliedro_r2 = new javax.swing.JButton();
        poliedro_r3 = new javax.swing.JButton();
        poliedro_r4 = new javax.swing.JButton();
        id_vision = new javax.swing.JButton();
        tienda_claro = new javax.swing.JButton();
        extencion = new javax.swing.JButton();
        aplicativo = new javax.swing.JButton();
        biometrica = new javax.swing.JButton();
        claro_url = new javax.swing.JButton();
        versus = new javax.swing.JButton();
        gsmarena = new javax.swing.JButton();
        desactivado = new javax.swing.JButton();
        notus = new javax.swing.JButton();
        agendamiento = new javax.swing.JButton();
        claro_web = new javax.swing.JButton();
        claro_home = new javax.swing.JButton();
        nueva_extension = new javax.swing.JButton();
        crm = new javax.swing.JButton();
        google_maps = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OneLock acceso directo");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APPS CLARO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MicrosoftTeams-image (6).png"))); // NOI18N

        poliedro_r1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        poliedro_r1.setForeground(new java.awt.Color(0, 0, 204));
        poliedro_r1.setText("Claro Poliedro R1");
        poliedro_r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliedro_r1ActionPerformed(evt);
            }
        });

        poliedro_r2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        poliedro_r2.setForeground(new java.awt.Color(0, 0, 204));
        poliedro_r2.setText("Claro Poliedro R2");
        poliedro_r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliedro_r2ActionPerformed(evt);
            }
        });

        poliedro_r3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        poliedro_r3.setForeground(new java.awt.Color(0, 0, 204));
        poliedro_r3.setText("Claro Poliedro R3");
        poliedro_r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliedro_r3ActionPerformed(evt);
            }
        });

        poliedro_r4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        poliedro_r4.setForeground(new java.awt.Color(0, 0, 204));
        poliedro_r4.setText("Claro Poliedro R4");
        poliedro_r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliedro_r4ActionPerformed(evt);
            }
        });

        id_vision.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        id_vision.setForeground(new java.awt.Color(0, 0, 204));
        id_vision.setText("Claro ID  Vision");
        id_vision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_visionActionPerformed(evt);
            }
        });

        tienda_claro.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tienda_claro.setForeground(new java.awt.Color(0, 0, 204));
        tienda_claro.setText("Tienda Claro");
        tienda_claro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tienda_claroActionPerformed(evt);
            }
        });

        extencion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        extencion.setForeground(new java.awt.Color(0, 0, 204));
        extencion.setText("Claro Extension OTP");
        extencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extencionActionPerformed(evt);
            }
        });

        aplicativo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        aplicativo.setForeground(new java.awt.Color(0, 0, 204));
        aplicativo.setText("Claro Aplicativo OTO");
        aplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicativoActionPerformed(evt);
            }
        });

        biometrica.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        biometrica.setForeground(new java.awt.Color(0, 0, 204));
        biometrica.setText("Biometria Facial");
        biometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biometricaActionPerformed(evt);
            }
        });

        claro_url.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        claro_url.setForeground(new java.awt.Color(0, 0, 204));
        claro_url.setText("Claro URL OTP");
        claro_url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claro_urlActionPerformed(evt);
            }
        });

        versus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        versus.setForeground(new java.awt.Color(0, 0, 204));
        versus.setText("Versus");
        versus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versusActionPerformed(evt);
            }
        });

        gsmarena.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        gsmarena.setForeground(new java.awt.Color(0, 0, 204));
        gsmarena.setText("GSMARENA");
        gsmarena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsmarenaActionPerformed(evt);
            }
        });

        desactivado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        desactivado.setForeground(new java.awt.Color(0, 0, 204));
        desactivado.setText("Desactivado");
        desactivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivadoActionPerformed(evt);
            }
        });

        notus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        notus.setForeground(new java.awt.Color(0, 0, 204));
        notus.setText("Notus");
        notus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notusActionPerformed(evt);
            }
        });

        agendamiento.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        agendamiento.setForeground(new java.awt.Color(0, 0, 204));
        agendamiento.setText("Agendamiento");
        agendamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamientoActionPerformed(evt);
            }
        });

        claro_web.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        claro_web.setForeground(new java.awt.Color(0, 0, 204));
        claro_web.setText("Claro Web");
        claro_web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claro_webActionPerformed(evt);
            }
        });

        claro_home.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        claro_home.setForeground(new java.awt.Color(0, 0, 204));
        claro_home.setText("Claro Home");
        claro_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claro_homeActionPerformed(evt);
            }
        });

        nueva_extension.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nueva_extension.setForeground(new java.awt.Color(0, 0, 204));
        nueva_extension.setText("Nueva Extension");
        nueva_extension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueva_extensionActionPerformed(evt);
            }
        });

        crm.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        crm.setForeground(new java.awt.Color(0, 0, 204));
        crm.setText("CRM");
        crm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crmActionPerformed(evt);
            }
        });

        google_maps.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        google_maps.setForeground(new java.awt.Color(0, 0, 204));
        google_maps.setText("Google Maps");
        google_maps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                google_mapsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(crm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(claro_web, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desactivado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(claro_url, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extencion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poliedro_r4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poliedro_r1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(poliedro_r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id_vision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(versus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(claro_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(google_maps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poliedro_r3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tienda_claro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biometrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gsmarena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agendamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nueva_extension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(poliedro_r1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(poliedro_r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poliedro_r3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(poliedro_r4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(id_vision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tienda_claro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extencion, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(aplicativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biometrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(claro_url, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(versus, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(gsmarena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desactivado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notus, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(agendamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crm, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(google_maps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nueva_extension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(claro_web, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(claro_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poliedro_r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliedro_r1ActionPerformed
        login logi = new login();
        logi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_poliedro_r1ActionPerformed

    private void poliedro_r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliedro_r2ActionPerformed
        // TODO add your handling code here:
        login logi = new login();
        logi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_poliedro_r2ActionPerformed

    private void poliedro_r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliedro_r3ActionPerformed
        // TODO add your handling code here:
        poliedro_r3 pol_r3 = new poliedro_r3();
        pol_r3.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_poliedro_r3ActionPerformed

    private void poliedro_r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliedro_r4ActionPerformed
        // TODO add your handling code here:
        poliedro_r4 pol_r4 = new poliedro_r4();
        pol_r4.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_poliedro_r4ActionPerformed

    private void id_visionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_visionActionPerformed
        // TODO add your handling code here:
        id_vision id_vi = new id_vision();
        id_vi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_id_visionActionPerformed

    private void tienda_claroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tienda_claroActionPerformed
        // TODO add your handling code here:
        tienda_claro t_claro = new tienda_claro();
        t_claro.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_tienda_claroActionPerformed

    private void extencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extencionActionPerformed
        // TODO add your handling code here:
        extension_otp ex_otp = new extension_otp();
        ex_otp.setVisible(true);
        dispose();
    }//GEN-LAST:event_extencionActionPerformed

    private void aplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicativoActionPerformed
        // TODO add your handling code here:
        aplicativo_otp ap_otp = new aplicativo_otp();
        ap_otp.setVisible(true);
        dispose();
    }//GEN-LAST:event_aplicativoActionPerformed

    private void biometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biometricaActionPerformed
        // TODO add your handling code here:
        claro_biometrica c_biometrica = new claro_biometrica();
        c_biometrica.setVisible(true);
        dispose();
    }//GEN-LAST:event_biometricaActionPerformed

    private void claro_urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claro_urlActionPerformed
        // TODO add your handling code here:
        claro_url c_url = new claro_url();
        c_url.setVisible(true);
        dispose();
    }//GEN-LAST:event_claro_urlActionPerformed

    private void versusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versusActionPerformed
        // TODO add your handling code here:
        versus vs = new versus();
        vs.setVisible(true);
        dispose();
    }//GEN-LAST:event_versusActionPerformed

    private void gsmarenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsmarenaActionPerformed
        // TODO add your handling code here:
        gsmarena gsmare = new gsmarena();
        gsmare.setVisible(true);
        dispose();
    }//GEN-LAST:event_gsmarenaActionPerformed

    private void desactivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivadoActionPerformed
        // TODO add your handling code here:
        desactivado desac = new desactivado();
        desac.setVisible(true);
        dispose();
    }//GEN-LAST:event_desactivadoActionPerformed

    private void notusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notusActionPerformed
        // TODO add your handling code here:
        notus nt = new notus();
        nt.setVisible(true);
        dispose();
    }//GEN-LAST:event_notusActionPerformed

    private void agendamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamientoActionPerformed
        // TODO add your handling code here:
        agendamiento agenda = new agendamiento();
        agenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_agendamientoActionPerformed

    private void crmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmActionPerformed
        // TODO add your handling code here:
        crm cr = new crm();
        cr.setVisible(true);
        dispose();
    }//GEN-LAST:event_crmActionPerformed

    private void google_mapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_google_mapsActionPerformed
        // TODO add your handling code here:
        google_maps g_maps = new google_maps();
        g_maps.setVisible(true);
        dispose();
    }//GEN-LAST:event_google_mapsActionPerformed

    private void nueva_extensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueva_extensionActionPerformed
        // TODO add your handling code here:
        nueva_extension n_extension = new nueva_extension();
        n_extension.setVisible(true);
        dispose();
    }//GEN-LAST:event_nueva_extensionActionPerformed

    private void claro_webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claro_webActionPerformed
        // TODO add your handling code here:
        claro_web c_web = new claro_web();
        c_web.setVisible(true);
        dispose();
    }//GEN-LAST:event_claro_webActionPerformed

    private void claro_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claro_homeActionPerformed
        // TODO add your handling code here:
        claro_home c_home = new claro_home();
        c_home.setVisible(true);
        dispose();
    }//GEN-LAST:event_claro_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(onelock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(onelock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(onelock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(onelock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new onelock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendamiento;
    private javax.swing.JButton aplicativo;
    private javax.swing.JButton biometrica;
    private javax.swing.JButton claro_home;
    private javax.swing.JButton claro_url;
    private javax.swing.JButton claro_web;
    private javax.swing.JButton crm;
    private javax.swing.JButton desactivado;
    private javax.swing.JButton extencion;
    private javax.swing.JButton google_maps;
    private javax.swing.JButton gsmarena;
    private javax.swing.JButton id_vision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton notus;
    private javax.swing.JButton nueva_extension;
    private javax.swing.JButton poliedro_r1;
    private javax.swing.JButton poliedro_r2;
    private javax.swing.JButton poliedro_r3;
    private javax.swing.JButton poliedro_r4;
    private javax.swing.JButton tienda_claro;
    private javax.swing.JButton versus;
    // End of variables declaration//GEN-END:variables
}
